apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-virtual-service-{{ .Values.namespace.name }}
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - common-istio-gateway
  http:
    - match:
      - headers:
          env:
            exact: {{ .Values.namespace.name }}
      route:
      - destination:
          host:
            app-service.{{ .Values.namespace.name }}.svc.cluster.local
          port:
            number: {{ .Values.app.ports.grpc.port }}
